name: ci
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs==1.1.2  # Added 2025 0223
      #- run: pip install mkdocs-backlinks-section-plugin # Added 2025 0223
      - run: pip install mkdocs-publisher  # Added 2023 0223
      - run: pip install mkdocs-material
      - run: pip install mkdocs-material-extensions
      - run: pip install pymdown-extensions
      - run: pip install mkdocs-roamlinks-plugin
      - run: pip install mkdocs-mermaid2-plugin
      - run: pip install mkdocs-callouts
      #-run: pip install markdown-callouts
      #- run: pip install mkdocs-backlinks  # Removed 2025 0223
      - run: mkdocs gh-deploy --force

